apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user
spec:
  memberOf: [rhdh-team]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  namespace: development
spec:
  memberOf: [default/rhdh-team]

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dcohen213
spec:
  memberOf: [rhdh-team]

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rhdh-team
  title: RHDH team
spec:
  type: team
  children: []

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sarah-architect
spec:
  memberOf: [group:default/mta-architects]

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dev-chen
spec:
  memberOf: [group:default/mta-developers]

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: mta-architects
  title: MTA Architects
spec:
  type: team
  children: []
  members: [user:default/sarah-architect]

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: mta-developers
  title: MTA Developers
spec:
  type: team
  children: []
  members: [user:default/dev-chen]
